// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadGotls returns the embedded CollectionSpec for gotls.
func loadGotls() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GotlsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load gotls: %w", err)
	}

	return spec, err
}

// loadGotlsObjects loads gotls and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*gotlsObjects
//	*gotlsPrograms
//	*gotlsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadGotlsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadGotls()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// gotlsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gotlsSpecs struct {
	gotlsProgramSpecs
	gotlsMapSpecs
	gotlsVariableSpecs
}

// gotlsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gotlsProgramSpecs struct {
	UprobeGotlsWrite *ebpf.ProgramSpec `ebpf:"uprobe_gotls_write"`
}

// gotlsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gotlsMapSpecs struct {
	GotlsCounters *ebpf.MapSpec `ebpf:"gotls_counters"`
	GotlsEvents   *ebpf.MapSpec `ebpf:"gotls_events"`
}

// gotlsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gotlsVariableSpecs struct {
	GotlsMaxCaptureBytes *ebpf.VariableSpec `ebpf:"gotls_max_capture_bytes"`
}

// gotlsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadGotlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type gotlsObjects struct {
	gotlsPrograms
	gotlsMaps
	gotlsVariables
}

func (o *gotlsObjects) Close() error {
	return _GotlsClose(
		&o.gotlsPrograms,
		&o.gotlsMaps,
	)
}

// gotlsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadGotlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type gotlsMaps struct {
	GotlsCounters *ebpf.Map `ebpf:"gotls_counters"`
	GotlsEvents   *ebpf.Map `ebpf:"gotls_events"`
}

func (m *gotlsMaps) Close() error {
	return _GotlsClose(
		m.GotlsCounters,
		m.GotlsEvents,
	)
}

// gotlsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadGotlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type gotlsVariables struct {
	GotlsMaxCaptureBytes *ebpf.Variable `ebpf:"gotls_max_capture_bytes"`
}

// gotlsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadGotlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type gotlsPrograms struct {
	UprobeGotlsWrite *ebpf.Program `ebpf:"uprobe_gotls_write"`
}

func (p *gotlsPrograms) Close() error {
	return _GotlsClose(
		p.UprobeGotlsWrite,
	)
}

func _GotlsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed gotls_arm64_bpfel.o
var _GotlsBytes []byte
