// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadJavatls returns the embedded CollectionSpec for javatls.
func loadJavatls() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_JavatlsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load javatls: %w", err)
	}

	return spec, err
}

// loadJavatlsObjects loads javatls and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*javatlsObjects
//	*javatlsPrograms
//	*javatlsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadJavatlsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadJavatls()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// javatlsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type javatlsSpecs struct {
	javatlsProgramSpecs
	javatlsMapSpecs
	javatlsVariableSpecs
}

// javatlsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type javatlsProgramSpecs struct {
	JavaKprobeSysIoctl *ebpf.ProgramSpec `ebpf:"java_kprobe_sys_ioctl"`
}

// javatlsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type javatlsMapSpecs struct {
	JavaCounters   *ebpf.MapSpec `ebpf:"java_counters"`
	JavaEvents     *ebpf.MapSpec `ebpf:"java_events"`
	JavaTargetPids *ebpf.MapSpec `ebpf:"java_target_pids"`
}

// javatlsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type javatlsVariableSpecs struct {
	JavaEnforcePidAllowlist *ebpf.VariableSpec `ebpf:"java_enforce_pid_allowlist"`
	JavaMaxCaptureBytes     *ebpf.VariableSpec `ebpf:"java_max_capture_bytes"`
}

// javatlsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadJavatlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type javatlsObjects struct {
	javatlsPrograms
	javatlsMaps
	javatlsVariables
}

func (o *javatlsObjects) Close() error {
	return _JavatlsClose(
		&o.javatlsPrograms,
		&o.javatlsMaps,
	)
}

// javatlsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadJavatlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type javatlsMaps struct {
	JavaCounters   *ebpf.Map `ebpf:"java_counters"`
	JavaEvents     *ebpf.Map `ebpf:"java_events"`
	JavaTargetPids *ebpf.Map `ebpf:"java_target_pids"`
}

func (m *javatlsMaps) Close() error {
	return _JavatlsClose(
		m.JavaCounters,
		m.JavaEvents,
		m.JavaTargetPids,
	)
}

// javatlsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadJavatlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type javatlsVariables struct {
	JavaEnforcePidAllowlist *ebpf.Variable `ebpf:"java_enforce_pid_allowlist"`
	JavaMaxCaptureBytes     *ebpf.Variable `ebpf:"java_max_capture_bytes"`
}

// javatlsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadJavatlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type javatlsPrograms struct {
	JavaKprobeSysIoctl *ebpf.Program `ebpf:"java_kprobe_sys_ioctl"`
}

func (p *javatlsPrograms) Close() error {
	return _JavatlsClose(
		p.JavaKprobeSysIoctl,
	)
}

func _JavatlsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed javatls_arm64_bpfel.o
var _JavatlsBytes []byte
