// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type libsslSslArgsT struct {
	Buf    uint64
	Ssl    uint64
	LenPtr uint64
}

// loadLibssl returns the embedded CollectionSpec for libssl.
func loadLibssl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LibsslBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load libssl: %w", err)
	}

	return spec, err
}

// loadLibsslObjects loads libssl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*libsslObjects
//	*libsslPrograms
//	*libsslMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLibsslObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLibssl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// libsslSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type libsslSpecs struct {
	libsslProgramSpecs
	libsslMapSpecs
	libsslVariableSpecs
}

// libsslProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type libsslProgramSpecs struct {
	UprobeSslRead       *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read"`
	UprobeSslReadEx     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ex"`
	UprobeSslWrite      *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx    *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex"`
	UretprobeSslRead    *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx  *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read_ex"`
	UretprobeSslWrite   *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write"`
	UretprobeSslWriteEx *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write_ex"`
}

// libsslMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type libsslMapSpecs struct {
	ActiveSslReadArgs  *ebpf.MapSpec `ebpf:"active_ssl_read_args"`
	ActiveSslWriteArgs *ebpf.MapSpec `ebpf:"active_ssl_write_args"`
	Events             *ebpf.MapSpec `ebpf:"events"`
	TargetPids         *ebpf.MapSpec `ebpf:"target_pids"`
}

// libsslVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type libsslVariableSpecs struct {
	EnforcePidAllowlist *ebpf.VariableSpec `ebpf:"enforce_pid_allowlist"`
	MaxCaptureBytes     *ebpf.VariableSpec `ebpf:"max_capture_bytes"`
}

// libsslObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLibsslObjects or ebpf.CollectionSpec.LoadAndAssign.
type libsslObjects struct {
	libsslPrograms
	libsslMaps
	libsslVariables
}

func (o *libsslObjects) Close() error {
	return _LibsslClose(
		&o.libsslPrograms,
		&o.libsslMaps,
	)
}

// libsslMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLibsslObjects or ebpf.CollectionSpec.LoadAndAssign.
type libsslMaps struct {
	ActiveSslReadArgs  *ebpf.Map `ebpf:"active_ssl_read_args"`
	ActiveSslWriteArgs *ebpf.Map `ebpf:"active_ssl_write_args"`
	Events             *ebpf.Map `ebpf:"events"`
	TargetPids         *ebpf.Map `ebpf:"target_pids"`
}

func (m *libsslMaps) Close() error {
	return _LibsslClose(
		m.ActiveSslReadArgs,
		m.ActiveSslWriteArgs,
		m.Events,
		m.TargetPids,
	)
}

// libsslVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLibsslObjects or ebpf.CollectionSpec.LoadAndAssign.
type libsslVariables struct {
	EnforcePidAllowlist *ebpf.Variable `ebpf:"enforce_pid_allowlist"`
	MaxCaptureBytes     *ebpf.Variable `ebpf:"max_capture_bytes"`
}

// libsslPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLibsslObjects or ebpf.CollectionSpec.LoadAndAssign.
type libsslPrograms struct {
	UprobeSslRead       *ebpf.Program `ebpf:"uprobe_ssl_read"`
	UprobeSslReadEx     *ebpf.Program `ebpf:"uprobe_ssl_read_ex"`
	UprobeSslWrite      *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx    *ebpf.Program `ebpf:"uprobe_ssl_write_ex"`
	UretprobeSslRead    *ebpf.Program `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx  *ebpf.Program `ebpf:"uretprobe_ssl_read_ex"`
	UretprobeSslWrite   *ebpf.Program `ebpf:"uretprobe_ssl_write"`
	UretprobeSslWriteEx *ebpf.Program `ebpf:"uretprobe_ssl_write_ex"`
}

func (p *libsslPrograms) Close() error {
	return _LibsslClose(
		p.UprobeSslRead,
		p.UprobeSslReadEx,
		p.UprobeSslWrite,
		p.UprobeSslWriteEx,
		p.UretprobeSslRead,
		p.UretprobeSslReadEx,
		p.UretprobeSslWrite,
		p.UretprobeSslWriteEx,
	)
}

func _LibsslClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed libssl_arm64_bpfel.o
var _LibsslBytes []byte
