package pcap

import (
	"net"

	"github.com/akitasoftware/go-utils/optionals"
	"github.com/google/gopacket"
	"github.com/google/gopacket/pcap"
	"github.com/pkg/errors"
)

// fileCaptureReader reads packets from a pcap file (e.g., generated by ecapture sidecar).
// It implements the pcapWrapper interface using a simple string type (the file path).
type fileCaptureReader string

func (f fileCaptureReader) capturePackets(
	done <-chan struct{},
	_, _ string,
	_ optionals.Optional[string],
) (<-chan gopacket.Packet, error) {
	handle, err := pcap.OpenOffline(string(f))
	if err != nil {
		return nil, errors.Wrapf(err, "failed to open pcap file %s", f)
	}

	out := make(chan gopacket.Packet)

	go func() {
		defer handle.Close()
		defer close(out)
		packetSource := gopacket.NewPacketSource(handle, handle.LinkType())
		for packet := range packetSource.Packets() {
			select {
			case <-done:
				return
			case out <- packet:
			}
		}
	}()

	return out, nil
}

// getInterfaceAddrs is not applicable for file-based capture
func (fileCaptureReader) getInterfaceAddrs(interfaceName string) ([]net.IP, error) {
	return nil, nil
}
