// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package openssl

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type OpenSSLTLSSslIoArgs struct {
	_      structs.HostLayout
	SslPtr uint64
	BufPtr uint64
}

// LoadOpenSSLTLS returns the embedded CollectionSpec for OpenSSLTLS.
func LoadOpenSSLTLS() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OpenSSLTLSBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load OpenSSLTLS: %w", err)
	}

	return spec, err
}

// LoadOpenSSLTLSObjects loads OpenSSLTLS and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*OpenSSLTLSObjects
//	*OpenSSLTLSPrograms
//	*OpenSSLTLSMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadOpenSSLTLSObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadOpenSSLTLS()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// OpenSSLTLSSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OpenSSLTLSSpecs struct {
	OpenSSLTLSProgramSpecs
	OpenSSLTLSMapSpecs
	OpenSSLTLSVariableSpecs
}

// OpenSSLTLSProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OpenSSLTLSProgramSpecs struct {
	HandleSslFree       *ebpf.ProgramSpec `ebpf:"handle_ssl_free"`
	HandleSslReadEntry  *ebpf.ProgramSpec `ebpf:"handle_ssl_read_entry"`
	HandleSslReadExit   *ebpf.ProgramSpec `ebpf:"handle_ssl_read_exit"`
	HandleSslSetFd      *ebpf.ProgramSpec `ebpf:"handle_ssl_set_fd"`
	HandleSslWriteEntry *ebpf.ProgramSpec `ebpf:"handle_ssl_write_entry"`
	HandleSslWriteExit  *ebpf.ProgramSpec `ebpf:"handle_ssl_write_exit"`
}

// OpenSSLTLSMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OpenSSLTLSMapSpecs struct {
	PendingRead  *ebpf.MapSpec `ebpf:"pending_read"`
	PendingWrite *ebpf.MapSpec `ebpf:"pending_write"`
	SslFdMap     *ebpf.MapSpec `ebpf:"ssl_fd_map"`
	TlsEvents    *ebpf.MapSpec `ebpf:"tls_events"`
}

// OpenSSLTLSVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OpenSSLTLSVariableSpecs struct {
}

// OpenSSLTLSObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadOpenSSLTLSObjects or ebpf.CollectionSpec.LoadAndAssign.
type OpenSSLTLSObjects struct {
	OpenSSLTLSPrograms
	OpenSSLTLSMaps
	OpenSSLTLSVariables
}

func (o *OpenSSLTLSObjects) Close() error {
	return _OpenSSLTLSClose(
		&o.OpenSSLTLSPrograms,
		&o.OpenSSLTLSMaps,
	)
}

// OpenSSLTLSMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadOpenSSLTLSObjects or ebpf.CollectionSpec.LoadAndAssign.
type OpenSSLTLSMaps struct {
	PendingRead  *ebpf.Map `ebpf:"pending_read"`
	PendingWrite *ebpf.Map `ebpf:"pending_write"`
	SslFdMap     *ebpf.Map `ebpf:"ssl_fd_map"`
	TlsEvents    *ebpf.Map `ebpf:"tls_events"`
}

func (m *OpenSSLTLSMaps) Close() error {
	return _OpenSSLTLSClose(
		m.PendingRead,
		m.PendingWrite,
		m.SslFdMap,
		m.TlsEvents,
	)
}

// OpenSSLTLSVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadOpenSSLTLSObjects or ebpf.CollectionSpec.LoadAndAssign.
type OpenSSLTLSVariables struct {
}

// OpenSSLTLSPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadOpenSSLTLSObjects or ebpf.CollectionSpec.LoadAndAssign.
type OpenSSLTLSPrograms struct {
	HandleSslFree       *ebpf.Program `ebpf:"handle_ssl_free"`
	HandleSslReadEntry  *ebpf.Program `ebpf:"handle_ssl_read_entry"`
	HandleSslReadExit   *ebpf.Program `ebpf:"handle_ssl_read_exit"`
	HandleSslSetFd      *ebpf.Program `ebpf:"handle_ssl_set_fd"`
	HandleSslWriteEntry *ebpf.Program `ebpf:"handle_ssl_write_entry"`
	HandleSslWriteExit  *ebpf.Program `ebpf:"handle_ssl_write_exit"`
}

func (p *OpenSSLTLSPrograms) Close() error {
	return _OpenSSLTLSClose(
		p.HandleSslFree,
		p.HandleSslReadEntry,
		p.HandleSslReadExit,
		p.HandleSslSetFd,
		p.HandleSslWriteEntry,
		p.HandleSslWriteExit,
	)
}

func _OpenSSLTLSClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed openssltls_bpfel.o
var _OpenSSLTLSBytes []byte
